[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#667eea"
backgroundColor = "#fafbfc"
secondaryBackgroundColor = "#ffffff"
textColor = "#000000"

[client]
showErrorDetails = false
