[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
enableStaticServing = true
runOnSave = false
allowRunOnSave = false

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[global]
developmentMode = false
suppressDeprecationWarnings = true
showWarningOnDirectExecution = false

[logger]
level = "info"